---
title: "Clustering"
author: "Isabel Amaya"
date: "18 de marzo de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
remove(list = ls())
#install.packages("rworldmap")
#install.packages("dplyr")

library(tidyverse)
library(dplyr)
library(data.table)
library(cluster)
library(rworldmap)
```

## Carga de datos
```{r}
datos <- read_csv("wbldata.csv")
attach(datos)
```
## Eliminación de columnas Si y No

```{r}
df = datos[,!grepl("No",colnames(datos))]
setDT(df)
ind = df[, lapply(.SD, function(x) grepl("No", x, perl=TRUE))] 
df <- df[,which(colSums(ind) == 0), with = FALSE]
```
```{r}
## columna de paises ISO3
Countries = df$country_code
## Eliminación de repetidos
Countries_2<-unique(Countries)
## eliminacion de less_income_group
df_less_income_group <- df[,-2]

```

```{r}
## columna de paises 
countriesNames = datos$country
## Sin repetidos
Countries_3<-unique(countriesNames)
```



## Plot Mapa Mundi


```{r}
mapByRegion(df_less_income_group, nameDataColumn="HAVING_CHILDREN", joinCode="ISO3", 
            nameJoinColumn="country_code", regionType="Stern", FUN="mean")
df_less_income_group
```

```{r}
mapByRegion(df_less_income_group, nameDataColumn="RUNNING BUSINESS", joinCode="ISO3", 
            nameJoinColumn="country_code", regionType="Stern", FUN="mean")

```
```{r}
#cluster y mapas
datos_cluster <- read_csv("/home/isa/Escritorio/holi.csv")
attach(datos_cluster)
datos_cluster
mapByRegion(datos_cluster, nameDataColumn="Kmeans_2009", joinCode="ISO3", 
            nameJoinColumn="country_code.o.", regionType="Stern", FUN="mean")



sPDF <- joinCountryData2Map(datos_cluster,
                            joinCode = "ISO3",
                            nameJoinColumn = "country_code.o.",
                            verbose = TRUE)

 mapParams <- mapPolys(sPDF, nameColumnToPlot="Kmeans_2009", mapRegion='world',
                          missingCountryCol='dark grey', catMethod=c(0,1,2,3,4),
                          colourPalette=c('green4','green1','greenyellow','yellow','yellow2','orange','coral','red','red3','red4','orchid','orchid1',' orchid2','magenta'),
                          #colourPalette=c('orchid','orchid1',' orchid2','magenta',' magenta1 ','magenta2 ','mediumorchid1',' mediumorchid2',' mediumorchid3',' mediumorchid4','hotpink4'),
                          addLegend=TRUE,
                          oceanCol='light blue')
    mtext("[Grey Color: No Data Available]",side=1,line=-1)

```
